### ISSUE TITLE
Add additional optional fields for data form collection

### ISSUE THREAD

**Issue by zachsa** [SAEON/data-portal#32]
- [x] Race
- [x] Gender
- [x] Age group
- [x] location (where do you live)
- [x] School vs organization

**Comment by zachsa** [comment]
@clairedavis-reddy - please let me know if there is other information that is required.

**Comment by clairedavis-reddy** [comment]
And if they are a University Student (post graduate or undergraduate) and which University they attend.

**Comment by zachsa** [comment]
@clairedavis-reddy - please let me know which age group brackets are useful. Currently they are:

```js
ageGroups = [
  'None',
  '< 18',
  '19 - 24',
  '25 - 30',
  '31 - 40',
  '> 41'
]
```

**Comment by zachsa** [comment]
- [ ] check form submissions succeed before deploying

**Comment by clairedavis-reddy** [comment]
Those age brackets are fine.
